### ISSUE TITLE
GPL Violation

### ISSUE THREAD

**Issue by InternalLoss** [EndlessBot/Endless#52]
Your code is currently potentially violating GPL, in various ways; while https://github.com/EndlessBot/Endless/pull/51 was submitted to try to help you come to terms with GPL, you rejected it for no reason. So, instead, I'll simply list the issues:

The GPL states that
```
 When you convey a covered work, you waive any legal power to forbid
circumvention of technological measures to the extent such circumvention
is effected by exercising rights under this License with respect to
the covered work, and you disclaim any intention to limit operation or
modification of the work as a means of enforcing, against the work's
users, your or third parties' legal rights to forbid circumvention of
technological measures.
```

You *do not* inform the user that you limit the administrative powers to your own Discord ID; [this code](https://cdn.discordapp.com/attachments/465118974749966337/502072956189671425/image0.png) is part of the startup check and makes the bot refuse to run, which is a way to limit the usage of this code. Your own pull, https://github.com/EndlessBot/Endless/pull/15, makes it obvious that this is your intention, so you've basically shot yourself in the foot there.

You explain you do not provide support, which *is* allowed under the GPL, however:
```
If you convey an object code work under this section in, or with, or
specifically for use in, a User Product, and the conveying occurs as
part of a transaction in which the right of possession and use of the
User Product is transferred to the recipient in perpetuity or for a
fixed term (regardless of how the transaction is characterized), the
Corresponding Source conveyed under this section must be accompanied
by the Installation Information.  But this requirement does not apply
if neither you nor any third party retains the ability to install
modified object code on the User Product (for example, the work has
been installed in ROM).

  The requirement to provide Installation Information does not include a
requirement to continue to provide support service, warranty, or updates
for a work that has been modified or installed by the recipient, or for
the User Product in which it has been modified or installed.  Access to a
network may be denied when the modification itself materially and
adversely affects the operation of the network or violates the rules and
protocols for communication across the network.

  Corresponding Source conveyed, and Installation Information provided,
in accord with this section must be in a format that is publicly
documented (and with an implementation available to the public in
source code form), and must require no special password or key for
unpacking, reading or copying.
```
The GPL clearly states that **Corresponding Source conveyed, and Installation Information provided,
in accord with this section must be in a format that is publicly
documented**. You do not provide installation information, such as SQL tables, or similar required files. Again, PR 51 was meant to try to fix this, but you rejected it and locked it, being very anti-GPL - please respect your own license that you released your code under, because you can and have violated the GPL by being such anti-modification.

**Comment by InternalLoss** [comment]
For transparency, this issue has been added to Web Archive: http://web.archive.org/web/20181017110602/https://github.com/EndlessBot/Endless/issues/52

**Comment by MikeModder** [comment]
While I'm not a super OSS freak I cannot simply ignore this. The violation has been brought to your attention before, which ended up with a banned/ignored offer of help. I understand your reasoning behind doing this -- I wouldn't want rampant clones of my bot either -- but using a license means that you and the people using your software list comply to it.

I'm sure I've spelled something eromg here but the gist is the same as above messages: if you're going to license your project, you should definitely stick to the license.

**Comment by InternalLoss** [comment]
The PR has been edited without permission from @caution3 - [this was the original PR statement](https://cdn.discordapp.com/attachments/465118974749966337/502082531873783808/image0.png)

**Comment by Artuto** [comment]
I can decide if I want to give info on installation or not.
